{% set version = "2.5" %}

package:
  name: pygplates
  version: {{ version }}

source:
  url: https://github.com/GPlates/GPlates/archive/refs/tags/GPlates-{{ version }}.tar.gz
  sha256: 8deea534b115d7748d76203e0ef9a3e47ee7f6e0582da49a2fc1c93bab8d0542

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - make  # [unix]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libdrm                             # [linux]
    - libegl-devel                       # [linux]
    - libgl-devel                        # [linux]
    - xorg-libx11                        # [linux]
    - xorg-libxau                        # [linux]
    - xorg-libxcomposite                 # [linux]
    - xorg-libxcursor                    # [linux]
    - xorg-libxdamage                    # [linux]
    - xorg-libxext                       # [linux]
    - xorg-libxi                         # [linux]
    - xorg-libxrandr                     # [linux]
    - xorg-libxrender                    # [linux]
    - xorg-libxscrnsaver                 # [linux]
    - xorg-libxtst                       # [linux]
    - xorg-libxxf86vm                    # [linux]
    - xorg-xorgproto                     # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
  host:
    - pip
    - python
    - setuptools
    - numpy
    - cgal-cpp
    - glew
    - libglu     # [linux]
    - xorg-libxfixes  # [linux]
    - qt-main
    - libboost-devel
    - libboost-python-devel
    - libgdal
    - proj
    - qwt
    - zlib
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - cgal-cpp
    - gmp        # [unix]
    - gmp       # [win]
    - glew
    - libglu     # [linux]
    - qt-main
    - libgdal
    - proj
    - qwt
    - zlib

test:
  source_files:
    - pygplates/test
  imports:
    - pygplates
  commands:
    - python pygplates/test/test.py

about:
  home: https://www.gplates.org/
  summary: 'Python library for fine-grained access to GPlates functionality'
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  doc_url: https://www.gplates.org/docs/pygplates/index.html
  dev_url: https://github.com/GPlates/GPlates

extra:
  recipe-maintainers:
    - jcannon-gplates
