{% set name = "pygplates" %}
{% set version = "0.47" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://earthbyte.org/webdav/ftp/earthbyte/pygplates/pygplates_0.47.0_src_build0.tar.bz2
  sha256: 3e4e83020e75be9e14c44e478591041f3bd1b3c87e9bea85e7e36b775ba80878

build:
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - make  # [unix]
    - {{ compiler('c') }}
    # Note: stdlib("c") should only be specified in the conda-forge feedstock (not for local conda builds).
    #       Otherwise local conda builds will give a dependency error that "c_win-64 does not exist".
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
  host:
    - python
    - pip
    - scikit-build-core
    - numpy
    - cgal-cpp
    - glew
    - libglu          # [linux]
    - xorg-libxfixes  # [linux]
    - qt-main
    - libboost-devel
    - libboost-python-devel
    - libgdal
    - proj
    - qwt
    - zlib
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - cgal-cpp
    - gmp        # [unix]
    - mpir       # [win]
    - glew
    - libglu     # [linux]
    - qt-main
    - libgdal
    - proj
    - qwt
    - zlib

test:
  source_files:
    - pygplates/test
  imports:
    - pygplates
  commands:
    - python pygplates/test/test.py

about:
  home: https://www.gplates.org/
  summary: 'Python library for fine-grained access to GPlates functionality'
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  doc_url: https://www.gplates.org/docs/pygplates/index.html
  dev_url: https://github.com/GPlates/GPlates

extra:
  recipe-maintainers:
    - jcannon-gplates
